" Configuration for vim
" Last changed: 2020-04-06
"
syntax on
filetype plugin indent on
set bs=indent,eol,start
set history=500
set scrolloff=0             " No breathing room
set number
set mouse=		    " No mouse capture

set ruler                   " Show the cursor position all the time
set showcmd
set showmode
set ls=2                    " Always show status bar

if &shell =~# 'fish$'
    set shell=bash
endif

set wrap linebreak breakindent
set showbreak=↪
set nolist
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:•,extends:⟩,precedes:⟨
set autoindent
" t = autowrap text using textwidth
" c = autowrap comments using textwidth
" q = allow formatting of comments with "gq"
" n = recognize numbered lists for formatting purposes
" 1 = do not break line after a one-letter word
set formatoptions=tcqn1
set tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab
set number
set foldmarker={{{,}}}
set foldlevel=0
set foldmethod=marker

set encoding=utf-8
set laststatus=2            " Always put a status line in
set showtabline=2           " Show a tabbar on top, always

set ignorecase              " Ignore case in searches
set smartcase               " But care about case if I enter capitals
set gdefault                " Subsitutions are global ('g') by default
set incsearch               " Do incremental searching
set nohlsearch              " Do not hightlight all matches in a search
set conceallevel=0          " After considerable thought, conceal is evil

set backup
set backupdir=$HOME/.nvim_backups,/tmp
set directory=/tmp,$HOME/.nvim_backups

set undofile
set undodir=$HOME/.nvim_undo,/tmp

set grepprg=ack\ --nogroup\ --column
set grepformat=%f:%l:%c:%m

" Use bash-style tab completion: first tab shows longest common string and
" subsequent tabs list all choices
set wildmode=longest,list

set hidden
set title
set shortmess=atIF

set statusline=[%<%.20f][%{&fenc==''?&enc:&fenc}]%y%m%r%h
set statusline+=%=%([Line:\ %l\ Column:\ %c\ %P]%)

set termguicolors
set background=light
colorscheme PaperColor

set printoptions:paper:letter,header:0,syntax:n
set printfont:Consolas

" vim: set ts=8 sw=4 tw=78 et :
