return {
    "dcampos/nvim-snippy",
    "dstein64/vim-startuptime",
    "farmergreg/vim-lastplace",
    "kylechui/nvim-surround",
    "lambdalisue/suda.vim",
    "lukas-reineke/indent-blankline.nvim",
    -- "m4xshen/autoclose.nvim",
    "neovim/nvim-lspconfig",
    "nvim-treesitter/nvim-treesitter-textobjects",
    "nvim-treesitter/nvim-treesitter",
    "savq/paq-nvim",
    "stevearc/conform.nvim",
    {
        "telemachus/autoclose.nvim",
        branch = "multibyte",
    },
    "telemachus/github-nvim-theme",
    {
        "telemachus/refinery.nvim",
        branch = "setup",
    },
    "telemachus/vim-colors-off",
    "uga-rosa/utf8.nvim",
}
