return {
    "dcampos/nvim-snippy",
    "dstein64/vim-startuptime",
    "farmergreg/vim-lastplace",
    "kylechui/nvim-surround",
    "lambdalisue/suda.vim",
    "lukas-reineke/indent-blankline.nvim",
    "m4xshen/autoclose.nvim",
    "neovim/nvim-lspconfig",
    "numToStr/Comment.nvim",
    "nvim-treesitter/nvim-treesitter-textobjects",
    "nvim-treesitter/nvim-treesitter",
    "stevearc/conform.nvim",
    {
        "telemachus/github-nvim-theme",
        branch = "pinned",
        pin = true,
    },
    "telemachus/nvim-dotfiles",
    "tpope/vim-markdown",
    "tpope/vim-repeat",
    "uga-rosa/utf8.nvim",
}
