local opt_local = vim.opt_local
opt_local.foldenable = false
opt_local.foldcolumn = "0"
opt_local.number = false
opt_local.relativenumber = false
opt_local.statuscolumn = ""
opt_local.comments = ""
opt_local.formatoptions = "1tn"
opt_local.textwidth = 72
opt_local.colorcolumn = "73"
opt_local.list = true
opt_local.spell = true
opt_local.signcolumn = "no"
opt_local.formatprg = "par -w72q"
